# Generated by Django 3.2 on 2024-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='myuser',
            name='jwt',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
