# Generated by Django 3.2 on 2024-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240619_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='jwt',
        ),
    ]
