"""Constants used in YAMDB."""

USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'
MAX_LENGTH_ROLE = 50
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
