# Generated by Django 3.2 on 2024-06-26 21:33

import reviews.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.validate.validate_year], verbose_name='Год выпуска'),
        ),
    ]
