# Generated by Django 3.2 on 2024-07-02 21:14

from django.db import migrations, models
import reviews.validate


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20240630_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validate.validate_year], verbose_name='Год выпуска'),
        ),
    ]
